name: voice_based_sos_system
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  porcupine_flutter: ^2.2.0
  hexcolor: ^3.0.1
  background_sms: ^0.0.4
  geolocator: ^9.0.2
  shared_preferences: ^2.0.17
  fluttertoast: ^8.1.3
  permission_handler: ^10.2.0
  noise_meter: ^3.2.0
  cupertino_icons: ^1.0.2
  awesome_dropdown: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/HelpMe.ppn
    - assets/Emergency.ppn
